### PR TITLE
Rename to eslint-plugin

### PR DESCRIPTION
**Pull request by kanongil**
Handles the in-repo part of #21.

Once merged, the following still needs to be done:

1. Rename this github repository.
1. Create and publish the package. Maybe as v5.0 for good measure?
1. Update lab https://github.com/hapijs/lab/pull/990.
1. Update [hapi.dev](https://github.com/hapijs/hapi.dev/blob/a3b805bb3386d3b55fe26957423a1aa65ca574b8/assets/js/getModuleInfo.js#L31).
1. Eventually, update local lab dependency with v24 release.

Fortunately, no hapi project have any `eslint-disable` lines containing `@hapi/hapi` rules, so it should provide a clean update.

### CODE REVIEW

**Comment by kanongil** [comment]
CI might also need to be hooked, and old repos & packages will need to be deprecated as well.

**Review by cjihrig — APPROVED** [review]

**Comment by cjihrig** [comment]
There is a conflict in package.json.

**Comment by kanongil** [comment]
Yeah, the conflict came from the release you just made, since the version is next to the package name.

**Comment by cjihrig** [comment]
Yea, I figured that was that was the case, but I wanted to get a release out before landing more breaking changes.

**Pull request merged**
